from . import (
  AC,
  AC_CIRCUITS,
  DHW,
  DHW_CIRCUITS,
  HC,
  HEATING_CIRCUITS
)

SYSTEM_MODEL = "model"
POINTTAPI = "POINTTAPI"

CIRCUIT_TYPES = {HC: HEATING_CIRCUITS, DHW: DHW_CIRCUITS, AC: AC_CIRCUITS}
